services:
    Dominique92.Reference.listener:
        class: Dominique92\Reference\event\listener
        arguments:
            - @dbal.conn
            - @request
            - @template
            - @user
            - @auth
            - @ext.manager
            - %core.root_path%
        tags:
            - { name: event.listener }
