services:
    Dominique92.Organiser.listener:
        class: Dominique92\Organiser\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }
